name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.25.1]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0

      - name: Build
        run: go build ./...

      - name: Run tests and generate coverage
        run: go test -coverprofile="coverage-go-${{ matrix.go-version }}.out" ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: "coverage-go-${{ matrix.go-version }}"
          path: "coverage-go-${{ matrix.go-version }}.out"
