name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.25.0]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0

      - name: Build
        run: go build ./...

      - name: Run tests
        run: go test ./...
